# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python3 package

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
  

    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
    
    - name: checkout
      uses: action/checkout@v1
    - name: Run python3
      run: |
        python3 addition.py
